export { ParserRegistry } from "./registry";
export { normalizeAmount, extractAmount } from "./amount";
export { upiParser } from "./upi";
export { creditCardParser } from "./credit-card";
export { bankTransferParser } from "./bank-transfer";
export { sipParser } from "./sip";
export { loanParser } from "./loan";
export { createParserPipeline, parseEmail, parseEmails } from "./pipeline";
export { aiFallbackParser, createAiFallbackParser, parseAiResponse, buildPrompt } from "./ai-fallback";
export type { SpawnFn } from "./ai-fallback";
